# Generated by Django 5.0.7 on 2024-07-27 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subreddit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('bio', models.TextField(blank=True, null=True)),
                ('profilePicture', models.ImageField(default='media/profilePricture/default.svg', upload_to='media/profilePicture')),
                ('moderator', models.ManyToManyField(related_name='Moderator', to='subreddit.subreddit')),
                ('subscribedSubreddits', models.ManyToManyField(related_name='subscribers', to='subreddit.subreddit')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
