# Generated by Django 5.0.7 on 2024-07-27 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profilePicture',
            new_name='profile_picture',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='subscribedSubreddits',
            new_name='subscribed_subreddits',
        ),
    ]
