# Generated by Django 5.0.7 on 2024-07-28 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_comment_createdat_alter_post_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.TextField(choices=[('Public', 'public'), ('Private', 'private'), ('Members', 'members')], default='Public'),
        ),
    ]
