# Generated by Django 5.0.7 on 2024-07-26 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subreddit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('dob', models.DateField()),
                ('bio', models.TextField(blank=True, null=True)),
                ('profilePicture', models.TextField(default='./static/profilePricture/default.svg')),
                ('moderator', models.ManyToManyField(related_name='Moderator', to='subreddit.subreddit')),
                ('subscribedSubreddits', models.ManyToManyField(related_name='subscribers', to='subreddit.subreddit')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
